version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io

      - run:
          name: Build Docker Image with Tag
          command: |
            cd code/
            docker build -t $DOCKER_USERNAME/django-chat-app:$CIRCLE_SHA1 .

      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/django-chat-app:$CIRCLE_SHA1

  deploy:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "YOUR_KEY_FINGERPRINT"

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST "
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
        
            echo '🔍 Stop container on port 8000 if exists...' &&
            docker ps -q --filter 'publish=8000' | xargs -r docker stop &&
            docker ps -a -q --filter 'publish=8000' | xargs -r docker rm &&
        
            echo '📦 Pull image...' &&
            docker pull $DOCKER_USERNAME/django-chat-app:$CIRCLE_SHA1 &&

            echo '🚀 Run container...' &&
            docker run -d --name django-chat-app -p 8000:8000 $DOCKER_USERNAME/django-chat-app:$CIRCLE_SHA1
            "

workflows:
  version: 2
  build-push-deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push
