apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: django-chat-app-hpa
  namespace: django-chat-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: django-chat-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10